# Generated by Django 3.2.9 on 2021-11-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_alter_factura_id_impuesto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='cliente',
            new_name='id_cliente',
        ),
    ]
