# Generated by Django 3.2.9 on 2021-11-08 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_auto_20211108_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='id_descuento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facturacion.descuento'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='id_impuesto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='facturacion.impuesto'),
        ),
    ]
