# Generated by Django 3.2.9 on 2021-11-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_auto_20211103_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='porcentaje',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='porcentaje',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(),
        ),
    ]
