# Generated by Django 3.2.9 on 2021-11-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_auto_20211103_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('PA', 'Pagada'), ('AN', 'Anulada')], default='PE', max_length=2),
        ),
    ]
