# Generated by Django 3.2.9 on 2021-11-05 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_factura_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='id_descuento',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='facturacion.descuento'),
        ),
    ]
