# Generated by Django 3.2.9 on 2021-11-05 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_alter_factura_id_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='id_impuesto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facturacion.impuesto'),
        ),
    ]
