# Generated by Django 3.2.9 on 2021-11-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_auto_20211105_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='factura',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
