# Generated by Django 3.2.9 on 2021-11-08 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_auto_20211108_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='impuesto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='facturacion.impuesto'),
        ),
    ]
